export const SCHOOLS = [
  {
    id: "clemson",
    name: "Clemson University",
    shortName: "Clemson",
    mascot: "Tigers",
    primaryColor: "#F56600",
    secondaryColor: "#522D80",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://clemsontigers.com",
    sports: ["lacrosse"]
  },
  {
    id: "unc",
    name: "UNC Chapel Hill",
    shortName: "UNC",
    mascot: "Tar Heels",
    primaryColor: "#4B9CD3",
    secondaryColor: "#13294B",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://goheels.com",
    sports: ["lacrosse"]
  },
  {
    id: "maryland",
    name: "University of Maryland",
    shortName: "Maryland",
    mascot: "Terrapins",
    primaryColor: "#E03A3E",
    secondaryColor: "#FFD520",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big Ten",
    athleticUrl: "https://umterps.com",
    sports: ["lacrosse"]
  },
  {
    id: "syracuse",
    name: "Syracuse University",
    shortName: "Syracuse",
    mascot: "Orange",
    primaryColor: "#F76900",
    secondaryColor: "#0D1B2A",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://cuse.com",
    sports: ["lacrosse"]
  },
  {
    id: "duke",
    name: "Duke University",
    shortName: "Duke",
    mascot: "Blue Devils",
    primaryColor: "#003087",
    secondaryColor: "#E8E8E8",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://goduke.com",
    sports: ["lacrosse"]
  },
  {
    id: "notre-dame",
    name: "Notre Dame",
    shortName: "Notre Dame",
    mascot: "Fighting Irish",
    primaryColor: "#0C2340",
    secondaryColor: "#C99700",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://und.com",
    sports: ["lacrosse"]
  },
  {
    id: "virginia",
    name: "University of Virginia",
    shortName: "Virginia",
    mascot: "Cavaliers",
    primaryColor: "#232D4B",
    secondaryColor: "#F84C1E",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://virginiasports.com",
    sports: ["lacrosse"]
  },
  {
    id: "johns-hopkins",
    name: "Johns Hopkins",
    shortName: "Hopkins",
    mascot: "Blue Jays",
    primaryColor: "#68ACE5",
    secondaryColor: "#000000",
    textOnPrimary: "#000000",
    division: "D1",
    conference: "Big Ten",
    athleticUrl: "https://hopkinssports.com",
    sports: ["lacrosse"]
  },
  {
    id: "penn-state",
    name: "Penn State",
    shortName: "Penn State",
    mascot: "Nittany Lions",
    primaryColor: "#1E407C",
    secondaryColor: "#CCCCCC",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big Ten",
    athleticUrl: "https://gopsusports.com",
    sports: ["lacrosse"]
  },
  {
    id: "nc-state",
    name: "NC State",
    shortName: "NC State",
    mascot: "Wolfpack",
    primaryColor: "#CC0000",
    secondaryColor: "#4D4D4D",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://gopack.com",
    sports: ["lacrosse"]
  },
  {
    id: "ohio-state",
    name: "Ohio State",
    shortName: "Ohio State",
    mascot: "Buckeyes",
    primaryColor: "#BB0000",
    secondaryColor: "#666666",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big Ten",
    athleticUrl: "https://ohiostatebuckeyes.com",
    sports: ["lacrosse"]
  },
  {
    id: "michigan",
    name: "University of Michigan",
    shortName: "Michigan",
    mascot: "Wolverines",
    primaryColor: "#00274C",
    secondaryColor: "#FFCB05",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big Ten",
    athleticUrl: "https://mgoblue.com",
    sports: ["lacrosse"]
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    shortName: "Georgetown",
    mascot: "Hoyas",
    primaryColor: "#041E42",
    secondaryColor: "#63666A",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big East",
    athleticUrl: "https://guhoyas.com",
    sports: ["lacrosse"]
  },
  {
    id: "boston-college",
    name: "Boston College",
    shortName: "Boston College",
    mascot: "Eagles",
    primaryColor: "#8B2035",
    secondaryColor: "#AE9142",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ACC",
    athleticUrl: "https://bceagles.com",
    sports: ["lacrosse"]
  },
  {
    id: "denver",
    name: "University of Denver",
    shortName: "Denver",
    mascot: "Pioneers",
    primaryColor: "#864024",
    secondaryColor: "#C8A951",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "ASUN",
    athleticUrl: "https://denverpioneers.com",
    sports: ["lacrosse"]
  },
  {
    id: "loyola-maryland",
    name: "Loyola Maryland",
    shortName: "Loyola MD",
    mascot: "Greyhounds",
    primaryColor: "#006633",
    secondaryColor: "#54565B",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Patriot",
    athleticUrl: "https://loyolagreyhounds.com",
    sports: ["lacrosse"]
  },
  {
    id: "princeton",
    name: "Princeton University",
    shortName: "Princeton",
    mascot: "Tigers",
    primaryColor: "#FF6600",
    secondaryColor: "#000000",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Ivy League",
    athleticUrl: "https://goprincetontigers.com",
    sports: ["lacrosse"]
  },
  {
    id: "yale",
    name: "Yale University",
    shortName: "Yale",
    mascot: "Bulldogs",
    primaryColor: "#00356B",
    secondaryColor: "#888888",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Ivy League",
    athleticUrl: "https://yalebulldogs.com",
    sports: ["lacrosse"]
  },
  {
    id: "harvard",
    name: "Harvard University",
    shortName: "Harvard",
    mascot: "Crimson",
    primaryColor: "#A51C30",
    secondaryColor: "#888888",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Ivy League",
    athleticUrl: "https://gocrimson.com",
    sports: ["lacrosse"]
  },
  {
    id: "cornell",
    name: "Cornell University",
    shortName: "Cornell",
    mascot: "Big Red",
    primaryColor: "#B31B1B",
    secondaryColor: "#777777",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Ivy League",
    athleticUrl: "https://cornellbigred.com",
    sports: ["lacrosse"]
  },
  {
    id: "villanova",
    name: "Villanova University",
    shortName: "Villanova",
    mascot: "Wildcats",
    primaryColor: "#00529B",
    secondaryColor: "#009CE0",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big East",
    athleticUrl: "https://villanova.com",
    sports: ["lacrosse"]
  },
  {
    id: "marquette",
    name: "Marquette University",
    shortName: "Marquette",
    mascot: "Golden Eagles",
    primaryColor: "#003595",
    secondaryColor: "#FFCF01",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Big East",
    athleticUrl: "https://gomarquette.com",
    sports: ["lacrosse"]
  },
  {
    id: "james-madison",
    name: "James Madison University",
    shortName: "JMU",
    mascot: "Dukes",
    primaryColor: "#450084",
    secondaryColor: "#CBB677",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Sun Belt",
    athleticUrl: "https://jmusports.com",
    sports: ["lacrosse"]
  },
  {
    id: "stony-brook",
    name: "Stony Brook University",
    shortName: "Stony Brook",
    mascot: "Seawolves",
    primaryColor: "#990000",
    secondaryColor: "#808080",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "America East",
    athleticUrl: "https://stonybrookathletics.com",
    sports: ["lacrosse"]
  },
  {
    id: "army",
    name: "Army West Point",
    shortName: "Army",
    mascot: "Black Knights",
    primaryColor: "#4A4A4A",
    secondaryColor: "#C8A951",
    textOnPrimary: "#FFFFFF",
    division: "D1",
    conference: "Patriot",
    athleticUrl: "https://goarmywestpoint.com",
    sports: ["lacrosse"]
  },
  {
    id: "undecided",
    name: "Undecided",
    shortName: "My Goal",
    mascot: "",
    primaryColor: "#2A2A3E",
    secondaryColor: "#4A4A6A",
    textOnPrimary: "#F0EAFB",
    division: null,
    conference: null,
    athleticUrl: null,
    sports: ["lacrosse"]
  }
];

export default SCHOOLS;
