#!/usr/bin/env node
/**
 * Regenerates src/data/rosterData.js from scripts/output/athletics.json.
 *
 * For every school that scraped successfully, the real coaching staff and
 * roster replace the old placeholder data. Schools that failed keep whatever
 * they had before (placeholder or a prior good scrape), so a partial scrape
 * never wipes existing data.
 *
 * Usage: node scripts/buildRosterData.js
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { SCHOOLS } from '../src/data/schools.js'
import { ROSTER_DATA as EXISTING } from '../src/data/rosterData.js'
import { REAL_COACHING_STAFF } from '../src/data/realCoachingStaff.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ATHLETICS_FILE = join(__dirname, 'output', 'athletics.json')
const ROSTER_DATA_PATH = join(__dirname, '../src/data/rosterData.js')

if (!existsSync(ATHLETICS_FILE)) {
  console.error('No scripts/output/athletics.json. Run: node scripts/scrapeAthletics.js --all')
  process.exit(1)
}

const scraped = JSON.parse(readFileSync(ATHLETICS_FILE, 'utf-8'))

// realCoachingStaff.js keys schools without hyphens, with a couple of short forms.
const REAL_KEY_ALIAS = { 'loyola-maryland': 'loyolamd', 'james-madison': 'jmu' }
const realStaffFor = (id) =>
  (REAL_COACHING_STAFF[id] ||
    REAL_COACHING_STAFF[REAL_KEY_ALIAS[id]] ||
    REAL_COACHING_STAFF[id.replace(/-/g, '')])?.coachingStaff

const result = {}
let scrapedRosters = 0
let coachFallback = 0
let placeholder = 0

for (const school of SCHOOLS) {
  if (school.id === 'undecided') continue
  const data = scraped[school.id]
  const existing = EXISTING[school.id]
  const realStaff = realStaffFor(school.id)

  const hasScrapedStaff = data && data.ok && data.staff?.length
  const hasScrapedRoster = data && data.ok && data.players?.length

  // Coaches: live scrape (richest, includes photos) > hand-collected real
  // coaches from the athletics-site sweep > whatever placeholder existed.
  let coachingStaff
  if (hasScrapedStaff) {
    coachingStaff = data.staff.map((s) => ({
      name: s.name,
      title: s.title,
      email: s.email,
      phone: s.phone,
      ...(s.photo ? { photo: s.photo } : {}),
      placeholder: false,
    }))
  } else if (realStaff?.some((c) => c.placeholder === false)) {
    coachingStaff = realStaff
  } else {
    coachingStaff = existing?.coachingStaff || []
  }

  // Roster: only the live scrape has real player data; otherwise keep the
  // existing placeholder roster so the depth chart still renders.
  const roster = hasScrapedRoster
    ? data.players.map((p) => ({
        name: p.name,
        position: p.position,
        year: p.year,
        gradYear: p.gradYear,
        ...(p.jersey != null ? { jersey: p.jersey } : {}),
      }))
    : existing?.roster || []

  const entry = { coachingStaff, roster }
  if (hasScrapedRoster) entry.source = data.sourceUrl
  if (data?.ok && (hasScrapedStaff || hasScrapedRoster)) entry.lastUpdated = data.scrapedAt
  result[school.id] = entry

  if (hasScrapedRoster) {
    scrapedRosters++
  } else if (coachingStaff.some((c) => c.placeholder === false)) {
    coachFallback++
    console.warn(`  ${school.id}: real coaches (fallback), placeholder roster`)
  } else {
    placeholder++
    console.warn(`  ${school.id}: placeholder only (${data ? data.error : 'not scraped'})`)
  }
}

const header = `// Coaching staff and roster data for tracked D1 women's lacrosse programs.
//
// Generated by scripts/buildRosterData.js from data published on each school's
// official athletics website (see each entry's \`source\`). Do not edit by hand;
// re-run \`npm run refresh-data\` to update. Entries still marked
// \`placeholder: true\` could not be scraped and are awaiting a real source.
`

const body = `export const ROSTER_DATA = ${JSON.stringify(result, null, 2)};

/**
 * Returns the recruiting need level for a given school, position, and athlete's graduation year.
 * "high"   — 2 or more players at that position graduate at or before the athlete's grad year
 * "medium" — exactly 1 player graduating at or before that year
 * "low"    — position is stacked with underclassmen through that year
 */
export function getPositionNeed(schoolId, position, athleteGradYear) {
  const school = ROSTER_DATA[schoolId];
  if (!school) return "medium";
  const players = school.roster.filter(p => p.position === position);
  const graduating = players.filter(p => p.gradYear <= athleteGradYear).length;
  if (graduating >= 2) return "high";
  if (graduating === 1) return "medium";
  return "low";
}

export default ROSTER_DATA;
`

writeFileSync(ROSTER_DATA_PATH, `${header}\n${body}`)
console.log(`\nWrote ${ROSTER_DATA_PATH}`)
console.log(`  ${scrapedRosters} schools with live scraped rosters + coaches`)
console.log(`  ${coachFallback} schools with real coaches (fallback) + placeholder roster`)
console.log(`  ${placeholder} schools placeholder only`)
