#!/usr/bin/env node
// Pulls per-school admissions data (acceptance rate + SAT/ACT middle-50% ranges)
// from the U.S. Dept. of Education College Scorecard API and writes
// src/data/schoolAcademics.js. GPA is not provided by Scorecard.
//
// Usage: node scripts/fetchScorecard.mjs [API_KEY]   (defaults to DEMO_KEY)
import { writeFileSync } from 'fs';
import { SCHOOLS } from '../src/data/schools.js';

const API_KEY = process.argv[2] || process.env.DATA_GOV_API_KEY || 'DEMO_KEY';
const BASE = 'https://api.data.gov/ed/collegescorecard/v1/schools';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Official Scorecard names where they differ from our display names.
const NAME_OVERRIDE = {
  unc: 'University of North Carolina at Chapel Hill',
  maryland: 'University of Maryland-College Park',
  'notre-dame': 'University of Notre Dame',
  virginia: 'University of Virginia-Main Campus',
  'johns-hopkins': 'Johns Hopkins University',
  'penn-state': 'Pennsylvania State University-Main Campus',
  'nc-state': 'North Carolina State University at Raleigh',
  'ohio-state': 'Ohio State University-Main Campus',
  michigan: 'University of Michigan-Ann Arbor',
  'loyola-maryland': 'Loyola University Maryland',
  army: 'United States Military Academy',
};

const FIELDS = [
  'id',
  'school.name',
  'school.state',
  'latest.admissions.admission_rate.overall',
  'latest.admissions.sat_scores.25th_percentile.critical_reading',
  'latest.admissions.sat_scores.75th_percentile.critical_reading',
  'latest.admissions.sat_scores.25th_percentile.math',
  'latest.admissions.sat_scores.75th_percentile.math',
  'latest.admissions.act_scores.25th_percentile.cumulative',
  'latest.admissions.act_scores.75th_percentile.cumulative',
].join(',');

async function fetchSchool(name) {
  const url = `${BASE}?api_key=${encodeURIComponent(API_KEY)}&school.name=${encodeURIComponent(name)}&fields=${FIELDS}`;
  const res = await fetch(url);
  if (res.status === 429) throw new Error('rate-limited (429)');
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

const sumOrNull = (a, b) => (a != null && b != null ? a + b : null);

const out = {};
const report = [];

for (const s of SCHOOLS) {
  if (s.id === 'undecided') continue;
  const queryName = NAME_OVERRIDE[s.id] || s.name;
  try {
    const json = await fetchSchool(queryName);
    const total = json?.metadata?.total ?? 0;
    // `school.name` is a CONTAINS filter, so prefer an exact-name result.
    const results = json?.results || [];
    const exact = results.find((x) => (x['school.name'] || '').toLowerCase() === queryName.toLowerCase());
    const r = exact || results[0];
    const ambiguous = !exact && results.length > 1;
    if (!r) {
      report.push(`MISS  ${s.id.padEnd(16)} no match for "${queryName}"`);
      continue;
    }
    const satLow = sumOrNull(
      r['latest.admissions.sat_scores.25th_percentile.critical_reading'],
      r['latest.admissions.sat_scores.25th_percentile.math']
    );
    const satHigh = sumOrNull(
      r['latest.admissions.sat_scores.75th_percentile.critical_reading'],
      r['latest.admissions.sat_scores.75th_percentile.math']
    );
    const actLow = r['latest.admissions.act_scores.25th_percentile.cumulative'] ?? null;
    const actHigh = r['latest.admissions.act_scores.75th_percentile.cumulative'] ?? null;
    const acceptanceRate = r['latest.admissions.admission_rate.overall'] ?? null;

    out[s.id] = {
      acceptanceRate,
      satLow,
      satHigh,
      actLow,
      actHigh,
      source: 'College Scorecard',
      scorecardId: r.id,
      scorecardName: r['school.name'],
    };
    const flag = ambiguous ? ` [${total} matches, picked first — verify!]` : '';
    report.push(
      `OK    ${s.id.padEnd(16)} ${r['school.state']}  acc=${acceptanceRate != null ? (acceptanceRate * 100).toFixed(0) + '%' : '—'}  SAT=${satLow ?? '—'}-${satHigh ?? '—'}  ACT=${actLow ?? '—'}-${actHigh ?? '—'}  "${r['school.name']}"${flag}`
    );
  } catch (e) {
    report.push(`ERR   ${s.id.padEnd(16)} ${e.message}`);
  }
  await sleep(1500);
}

const body =
  `// Per-school admissions data from the U.S. Dept. of Education College Scorecard\n` +
  `// API (collegescorecard.ed.gov): acceptance rate + SAT/ACT middle-50% ranges.\n` +
  `// SAT range is the sum of the section 25th/75th percentiles. GPA is NOT provided\n` +
  `// by Scorecard. Generated by scripts/fetchScorecard.mjs — do not edit by hand.\n` +
  `export const ACADEMICS_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};\n` +
  `export const SCHOOL_ACADEMICS = ${JSON.stringify(out, null, 2)};\n` +
  `export default SCHOOL_ACADEMICS;\n`;

writeFileSync(new URL('../src/data/schoolAcademics.js', import.meta.url), body);

console.log(report.join('\n'));
console.log(`\nWrote ${Object.keys(out).length} schools to src/data/schoolAcademics.js`);
